--------------------------------------------------------
--  File created - Monday-June-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANAN_MONAN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."BANAN_MONAN" 
   (	"TEN_BAN" VARCHAR2(10 BYTE), 
	"TEN_MON" VARCHAR2(20 BYTE), 
	"TG_GOI" DATE, 
	"SUAT_AN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANG_GIA_BAN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."BANG_GIA_BAN" 
   (	"TEN_BAN" VARCHAR2(10 BYTE), 
	"GIA_BAN" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHUCVU
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."CHUCVU" 
   (	"TEN_CHUCVU" VARCHAR2(20 BYTE), 
	"TG_BATDAU" VARCHAR2(15 BYTE), 
	"TG_KETTHUC" VARCHAR2(15 BYTE), 
	"LUONG_THANG" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BAN_AN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."BAN_AN" 
   (	"TEN_BAN" VARCHAR2(10 BYTE), 
	"SOLUONG_GHE" NUMBER(5,0), 
	"TRANG_THAI" VARCHAR2(10 BYTE), 
	"GIA_BAN" NUMBER(10,0), 
	"RESERVED_TIME" DATE, 
	"TEN_DAY_DU" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISH_DATA
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."DISH_DATA" 
   (	"TEN_MON" VARCHAR2(20 BYTE), 
	"JANUARY" NUMBER, 
	"FEBRUARY" NUMBER, 
	"MARCH" NUMBER, 
	"APRIL" NUMBER, 
	"MAY" NUMBER, 
	"JUNE" NUMBER, 
	"JULY" NUMBER, 
	"AUGUST" NUMBER, 
	"SEPTEMBER" NUMBER, 
	"OCTOBER" NUMBER, 
	"NOVEMBER" NUMBER, 
	"DECEMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOANH_THU
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."DOANH_THU" 
   (	"THANG" VARCHAR2(15 BYTE), 
	"DOANH_THU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAY_REVENUE
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."DAY_REVENUE" 
   (	"DAYNUM" NUMBER, 
	"DOANH_THU" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DS_DATBAN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."DS_DATBAN" 
   (	"MA_DATBAN" NUMBER, 
	"RESERVED_TIME" DATE, 
	"GUEST_NUMBER" NUMBER, 
	"GUEST_EMAIL" VARCHAR2(40 BYTE), 
	"GUEST_NAME" VARCHAR2(30 BYTE), 
	"TEN_BAN" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOADON_NGAY
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."HOADON_NGAY" 
   (	"MA_HOADON" NUMBER(10,0), 
	"BAN_AN" VARCHAR2(10 BYTE), 
	"DANHSACH_MON" VARCHAR2(100 BYTE), 
	"THANHTIEN" NUMBER(10,0), 
	"NGAYGIO_THANHTOAN" DATE, 
	"SO_KHACH" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MON_AN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."MON_AN" 
   (	"TEN_MON" VARCHAR2(20 BYTE), 
	"GIA" NUMBER(10,0), 
	"MO_TA" VARCHAR2(50 BYTE), 
	"SL_DAT_THANG" VARCHAR2(20 BYTE), 
	"TEN_DAY_DU" VARCHAR2(20 BYTE), 
	"LOAI_THUCAN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."NHANVIEN" 
   (	"MANV" VARCHAR2(10 BYTE), 
	"HOTEN" VARCHAR2(30 BYTE), 
	"NGAYSINH" DATE, 
	"DIACHI" VARCHAR2(15 BYTE), 
	"SDT" NUMBER(12,0), 
	"EMAIL" VARCHAR2(35 BYTE), 
	"TK_NGANHANG" NUMBER(15,0), 
	"CHUC_VU" VARCHAR2(15 BYTE), 
	"GIOLAM_THANG" NUMBER, 
	"TEN_DAY_DU" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAIKHOAN
--------------------------------------------------------

  CREATE TABLE "C##BINHCHILI"."TAIKHOAN" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE), 
	"QUYENHAN" VARCHAR2(15 BYTE), 
	"SODUTK" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##BINHCHILI.BANAN_MONAN
SET DEFINE OFF;
Insert into C##BINHCHILI.BANAN_MONAN (TEN_BAN,TEN_MON,TG_GOI,SUAT_AN) values ('ban14','BunRieuCua',to_date('15-MAY-20 14:00','DD-MON-RR HH24:MI'),2);
Insert into C##BINHCHILI.BANAN_MONAN (TEN_BAN,TEN_MON,TG_GOI,SUAT_AN) values ('ban7','BunOc',to_date('10-MAY-20 21:03','DD-MON-RR HH24:MI'),3);
Insert into C##BINHCHILI.BANAN_MONAN (TEN_BAN,TEN_MON,TG_GOI,SUAT_AN) values ('ban7','BunRieuCua',to_date('10-MAY-20 21:03','DD-MON-RR HH24:MI'),1);
Insert into C##BINHCHILI.BANAN_MONAN (TEN_BAN,TEN_MON,TG_GOI,SUAT_AN) values ('ban17','ComChay',to_date('15-MAY-20 14:55','DD-MON-RR HH24:MI'),2);
Insert into C##BINHCHILI.BANAN_MONAN (TEN_BAN,TEN_MON,TG_GOI,SUAT_AN) values ('ban17','ComGa',to_date('29-DEC-19 21:03','DD-MON-RR HH24:MI'),5);
REM INSERTING into C##BINHCHILI.BANG_GIA_BAN
SET DEFINE OFF;
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban1',100000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban2',100000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban7',100000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban11',150000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban12',150000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban14',140000);
Insert into C##BINHCHILI.BANG_GIA_BAN (TEN_BAN,GIA_BAN) values ('ban17',150000);
REM INSERTING into C##BINHCHILI.CHUCVU
SET DEFINE OFF;
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('boiban1','8:00 AM','3:00 PM',5000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('boiban2','8:00 AM','3:00 PM',5000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('boiban3','8:00 AM','3:00 PM',5000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('boiban4','3:00 PM','10:00 PM',5000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('boiban5','3:00 PM','10:00 PM',5000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('thungan','8:00 AM','10:PM',4000000);
Insert into C##BINHCHILI.CHUCVU (TEN_CHUCVU,TG_BATDAU,TG_KETTHUC,LUONG_THANG) values ('daubep1','8:00 AM','3:00 PM',12000000);
REM INSERTING into C##BINHCHILI.BAN_AN
SET DEFINE OFF;
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban1',4,'reserved',100000,to_date('03-OCT-20 17:00','DD-MON-RR HH24:MI'),'Bàn s? 1');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban2',4,'empty',100000,null,'Bàn s? 2');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban11',6,'reserved',150000,to_date('03-JUN-20 17:00','DD-MON-RR HH24:MI'),'Bàn s? 3');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban12',6,'empty',150000,null,'Bàn s? 4');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban17',6,'full',150000,to_date('03-OCT-20 17:00','DD-MON-RR HH24:MI'),'Bàn s? 5');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban7',4,'full',100000,to_date('03-OCT-20 19:00','DD-MON-RR HH24:MI'),'Bàn s? 6');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban14',6,'reserved',140000,to_date('03-OCT-20 16:05','DD-MON-RR HH24:MI'),'Bàn s? 7');
Insert into C##BINHCHILI.BAN_AN (TEN_BAN,SOLUONG_GHE,TRANG_THAI,GIA_BAN,RESERVED_TIME,TEN_DAY_DU) values ('ban3',4,'empty',400000,null,'Bàn s? 8');
REM INSERTING into C##BINHCHILI.DISH_DATA
SET DEFINE OFF;
Insert into C##BINHCHILI.DISH_DATA (TEN_MON,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER) values ('BunRieuCua',0,0,0,0,0,0,0,0,0,0,0,0);
Insert into C##BINHCHILI.DISH_DATA (TEN_MON,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER) values ('BunOc',0,0,0,0,0,0,0,0,0,0,0,0);
Insert into C##BINHCHILI.DISH_DATA (TEN_MON,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER) values ('BunDauMet',0,0,0,0,0,0,0,0,0,0,0,0);
Insert into C##BINHCHILI.DISH_DATA (TEN_MON,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER) values ('ComGa',0,0,0,0,0,0,0,0,0,0,0,0);
Insert into C##BINHCHILI.DISH_DATA (TEN_MON,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER) values ('ComChay',0,0,0,0,0,0,0,0,0,0,0,0);
REM INSERTING into C##BINHCHILI.DOANH_THU
SET DEFINE OFF;
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('January',15);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('February',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('March',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('April',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('May',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('June',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('July',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('August',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('September',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('October',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('November',0);
Insert into C##BINHCHILI.DOANH_THU (THANG,DOANH_THU) values ('December',0);
REM INSERTING into C##BINHCHILI.DAY_REVENUE
SET DEFINE OFF;
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (1,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (2,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (3,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (4,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (5,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (6,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (7,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (8,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (9,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (10,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (11,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (12,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (13,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (14,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (15,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (16,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (17,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (18,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (19,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (20,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (21,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (22,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (23,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (24,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (25,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (26,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (27,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (28,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (29,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (30,'0');
Insert into C##BINHCHILI.DAY_REVENUE (DAYNUM,DOANH_THU) values (31,'0');
REM INSERTING into C##BINHCHILI.DS_DATBAN
SET DEFINE OFF;
Insert into C##BINHCHILI.DS_DATBAN (MA_DATBAN,RESERVED_TIME,GUEST_NUMBER,GUEST_EMAIL,GUEST_NAME,TEN_BAN) values (1234,to_date('03-JUN-20 17:00','DD-MON-RR HH24:MI'),913214,null,'Hoan','ban11');
Insert into C##BINHCHILI.DS_DATBAN (MA_DATBAN,RESERVED_TIME,GUEST_NUMBER,GUEST_EMAIL,GUEST_NAME,TEN_BAN) values (1254,to_date('03-OCT-20 17:00','DD-MON-RR HH24:MI'),8325324,null,'Lam','ban1');
REM INSERTING into C##BINHCHILI.HOADON_NGAY
SET DEFINE OFF;
Insert into C##BINHCHILI.HOADON_NGAY (MA_HOADON,BAN_AN,DANHSACH_MON,THANHTIEN,NGAYGIO_THANHTOAN,SO_KHACH) values (30183577,'ban7','Bún ?c,3,35000;Bún riêu cua,1,40000;Giá bàn,100000',245000,to_date('11-MAY-20 10:14','DD-MON-RR HH24:MI'),3);
Insert into C##BINHCHILI.HOADON_NGAY (MA_HOADON,BAN_AN,DANHSACH_MON,THANHTIEN,NGAYGIO_THANHTOAN,SO_KHACH) values (45687915,'ban17','Bún ?c,3,35000;Giá bàn,150000',255000,to_date('11-MAY-20 10:24','DD-MON-RR HH24:MI'),3);
REM INSERTING into C##BINHCHILI.MON_AN
SET DEFINE OFF;
Insert into C##BINHCHILI.MON_AN (TEN_MON,GIA,MO_TA,SL_DAT_THANG,TEN_DAY_DU,LOAI_THUCAN) values ('BunRieuCua',40000,null,'1','Bún riêu cua','MainCourse');
Insert into C##BINHCHILI.MON_AN (TEN_MON,GIA,MO_TA,SL_DAT_THANG,TEN_DAY_DU,LOAI_THUCAN) values ('BunOc',35000,null,'0','Bún ?c','MainCourse');
Insert into C##BINHCHILI.MON_AN (TEN_MON,GIA,MO_TA,SL_DAT_THANG,TEN_DAY_DU,LOAI_THUCAN) values ('BunDauMet',35000,null,'0','Bún ??u m?t','MainCourse');
Insert into C##BINHCHILI.MON_AN (TEN_MON,GIA,MO_TA,SL_DAT_THANG,TEN_DAY_DU,LOAI_THUCAN) values ('ComGa',25000,null,'0','C?m gà','MainCourse');
Insert into C##BINHCHILI.MON_AN (TEN_MON,GIA,MO_TA,SL_DAT_THANG,TEN_DAY_DU,LOAI_THUCAN) values ('ComChay',20000,null,'0','C?m chay','MainCourse');
REM INSERTING into C##BINHCHILI.NHANVIEN
SET DEFINE OFF;
Insert into C##BINHCHILI.NHANVIEN (MANV,HOTEN,NGAYSINH,DIACHI,SDT,EMAIL,TK_NGANHANG,CHUC_VU,GIOLAM_THANG,TEN_DAY_DU) values ('1001','NamAnh',to_date('03-OCT-02 00:00','DD-MON-RR HH24:MI'),'Ha Noi',904531931,'namanh@gmail.com',145045041504,'boiban1',0,'Nam Anh');
Insert into C##BINHCHILI.NHANVIEN (MANV,HOTEN,NGAYSINH,DIACHI,SDT,EMAIL,TK_NGANHANG,CHUC_VU,GIOLAM_THANG,TEN_DAY_DU) values ('1002','ThuHoai',to_date('31-DEC-00 07:00','DD-MON-RR HH24:MI'),'Ha Noi',904513931,'thuhoai@gmail.com',145045012504,'daubep1',0,'Thu Hoài');
Insert into C##BINHCHILI.NHANVIEN (MANV,HOTEN,NGAYSINH,DIACHI,SDT,EMAIL,TK_NGANHANG,CHUC_VU,GIOLAM_THANG,TEN_DAY_DU) values ('1216','HaLam',to_date('31-DEC-00 07:00','DD-MON-RR HH24:MI'),'Ha Noi',906716931,'haam@gmail.com',221545012504,'boiban3',0,'Hà Lâm');
REM INSERTING into C##BINHCHILI.TAIKHOAN
SET DEFINE OFF;
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('admin1','12345678','QUANLY',0);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('admin2','12345678','QUANLY',1000000);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('boiban1','12345678','NHANVIEN',0);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('thungan1','12345678','NHANVIEN',0);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('khachA','12345678','THUCKHACH',0);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('khachB','12345678','THUCKHACH',0);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('boiban2','12345678','NHANVIEN',1000);
Insert into C##BINHCHILI.TAIKHOAN (USERNAME,PASS,QUYENHAN,SODUTK) values ('boiban3','12345678','NHANVIEN',1000);
--------------------------------------------------------
--  DDL for Index SYS_C008934
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008934" ON "C##BINHCHILI"."DAY_REVENUE" ("DAYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008829
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008829" ON "C##BINHCHILI"."DS_DATBAN" ("MA_DATBAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008754
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008754" ON "C##BINHCHILI"."HOADON_NGAY" ("MA_HOADON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008738
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008738" ON "C##BINHCHILI"."BAN_AN" ("TEN_BAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008717
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008717" ON "C##BINHCHILI"."NHANVIEN" ("TK_NGANHANG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008716
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008716" ON "C##BINHCHILI"."NHANVIEN" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008714
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008714" ON "C##BINHCHILI"."NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008723
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008723" ON "C##BINHCHILI"."MON_AN" ("TEN_MON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008704
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008704" ON "C##BINHCHILI"."CHUCVU" ("TEN_CHUCVU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008691
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008691" ON "C##BINHCHILI"."TAIKHOAN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008761
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008761" ON "C##BINHCHILI"."BANG_GIA_BAN" ("TEN_BAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008823
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008823" ON "C##BINHCHILI"."DISH_DATA" ("TEN_MON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008931
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BINHCHILI"."SYS_C008931" ON "C##BINHCHILI"."DOANH_THU" ("THANG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger UPDATE_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."UPDATE_TABLE" after insert on ds_datban
for each row
begin
    update ban_an set trang_thai = 'reserved', reserved_time = :new.reserved_time 
    where ten_ban = :new.ten_ban;
end;
/
ALTER TRIGGER "C##BINHCHILI"."UPDATE_TABLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OPEN_PDBS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."OPEN_PDBS" 
  AFTER STARTUP ON DATABASE 
BEGIN 
   EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ALL OPEN'; 
END open_pdbs;
/
ALTER TRIGGER "C##BINHCHILI"."OPEN_PDBS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELETE_BANAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."DELETE_BANAN" after update of trang_thai on ban_an
for each row  WHEN (OLD.trang_thai = 'full' and NEW.trang_thai = 'empty') begin
   delete from banan_monan where ten_ban = :old.ten_ban;
end;
/
ALTER TRIGGER "C##BINHCHILI"."DELETE_BANAN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELETE_RESERVE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."DELETE_RESERVE" before delete on ds_datban
for each row
begin
     update ban_an set trang_thai = 'empty', reserved_time = null 
     where ten_ban = :old.ten_ban;
end;
/
ALTER TRIGGER "C##BINHCHILI"."DELETE_RESERVE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_AMOUNT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."UPDATE_AMOUNT" after insert on banan_monan
for each row
begin
    update mon_an set sl_dat_thang =  sl_dat_thang + :new.suat_an where ten_mon = :new.ten_mon;
end;
/
ALTER TRIGGER "C##BINHCHILI"."UPDATE_AMOUNT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_CALCULATE_BILL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BINHCHILI"."AUTO_CALCULATE_BILL" before update of trang_thai on ban_an
for each row  WHEN (OLD.trang_thai = 'full' and NEW.trang_thai = 'empty') declare

   thanhtien number := 0;
   descript varchar2(100);
   mahoadon number(10);
   cursor mon_an is select m.ten_mon as ten_mon, m.gia as gia , b.gia_ban as gia_ban, bm.suat_an as suat_an
   from banan_monan bm inner join mon_an m on bm.ten_mon = m.ten_mon
   inner join bang_gia_ban b on bm.ten_ban = b.ten_ban
   where bm.ten_ban = :OLD.ten_ban;
begin
   for recorder in mon_an
   loop
       thanhtien:= thanhtien + recorder.gia * recorder.suat_an ;
       descript:= descript || recorder.ten_mon || ',' || recorder.suat_an || ',' || recorder.gia|| ';' ;

   end loop;
   thanhtien:= thanhtien + :old.gia_ban;
   descript:= descript || 'Giá bàn,' || :old.gia_ban;
   mahoadon := dbms_random.value(10000000,99999999);
   insert into hoadon_ngay values(mahoadon,:old.ten_ban,descript,thanhtien,sysdate,0);
exception when no_data_found THEN
            dbms_output.put_line('Table does not exist');
end;
/
ALTER TRIGGER "C##BINHCHILI"."AUTO_CALCULATE_BILL" ENABLE;
--------------------------------------------------------
--  Constraints for Table BANAN_MONAN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" MODIFY ("SUAT_AN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" MODIFY ("TEN_BAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" MODIFY ("TEN_MON" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" MODIFY ("TG_GOI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANG_GIA_BAN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."BANG_GIA_BAN" MODIFY ("GIA_BAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BANG_GIA_BAN" ADD PRIMARY KEY ("TEN_BAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHUCVU
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."CHUCVU" MODIFY ("TEN_CHUCVU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."CHUCVU" MODIFY ("TG_BATDAU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."CHUCVU" MODIFY ("TG_KETTHUC" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."CHUCVU" MODIFY ("LUONG_THANG" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."CHUCVU" ADD CONSTRAINT "MINLUONG" CHECK (luong_thang>=0) ENABLE;
  ALTER TABLE "C##BINHCHILI"."CHUCVU" ADD PRIMARY KEY ("TEN_CHUCVU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BAN_AN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."BAN_AN" MODIFY ("TEN_BAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BAN_AN" MODIFY ("SOLUONG_GHE" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BAN_AN" MODIFY ("TRANG_THAI" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BAN_AN" MODIFY ("GIA_BAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."BAN_AN" ADD CONSTRAINT "MIN_GHE" CHECK (soluong_ghe >= 0) ENABLE;
  ALTER TABLE "C##BINHCHILI"."BAN_AN" ADD CONSTRAINT "STATUS" CHECK (trang_thai in ('empty','reserved','full')) ENABLE;
  ALTER TABLE "C##BINHCHILI"."BAN_AN" ADD CONSTRAINT "MIN_GIABAN" CHECK (gia_ban >= 0) ENABLE;
  ALTER TABLE "C##BINHCHILI"."BAN_AN" ADD PRIMARY KEY ("TEN_BAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISH_DATA
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("TEN_MON" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("JANUARY" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("FEBRUARY" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("MARCH" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("APRIL" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("MAY" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("JUNE" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("JULY" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("AUGUST" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("SEPTEMBER" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("OCTOBER" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("NOVEMBER" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" MODIFY ("DECEMBER" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DISH_DATA" ADD PRIMARY KEY ("TEN_MON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOANH_THU
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."DOANH_THU" MODIFY ("THANG" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DOANH_THU" MODIFY ("DOANH_THU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DOANH_THU" ADD PRIMARY KEY ("THANG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DAY_REVENUE
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."DAY_REVENUE" MODIFY ("DAYNUM" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DAY_REVENUE" MODIFY ("DOANH_THU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DAY_REVENUE" ADD PRIMARY KEY ("DAYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DS_DATBAN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" MODIFY ("MA_DATBAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" MODIFY ("RESERVED_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" MODIFY ("GUEST_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" ADD PRIMARY KEY ("MA_DATBAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" MODIFY ("TEN_BAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."DS_DATBAN" MODIFY ("GUEST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOADON_NGAY
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" MODIFY ("MA_HOADON" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" MODIFY ("BAN_AN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" MODIFY ("DANHSACH_MON" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" MODIFY ("THANHTIEN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" MODIFY ("NGAYGIO_THANHTOAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."HOADON_NGAY" ADD PRIMARY KEY ("MA_HOADON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MON_AN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."MON_AN" MODIFY ("TEN_MON" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."MON_AN" MODIFY ("GIA" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."MON_AN" ADD PRIMARY KEY ("TEN_MON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##BINHCHILI"."MON_AN" MODIFY ("SL_DAT_THANG" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."MON_AN" MODIFY ("TEN_DAY_DU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."MON_AN" MODIFY ("LOAI_THUCAN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("MANV" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("HOTEN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("NGAYSINH" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("DIACHI" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("SDT" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("TK_NGANHANG" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" MODIFY ("CHUC_VU" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" ADD PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##BINHCHILI"."NHANVIEN" ADD UNIQUE ("TK_NGANHANG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAIKHOAN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" MODIFY ("QUYENHAN" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" MODIFY ("SODUTK" NOT NULL ENABLE);
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" ADD CONSTRAINT "QUYEN" CHECK (quyenhan in ('QUANLY','NHANVIEN','THUCKHACH')) ENABLE;
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" ADD CONSTRAINT "MINSODU" CHECK (soduTK >= 0) ENABLE;
  ALTER TABLE "C##BINHCHILI"."TAIKHOAN" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANAN_MONAN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" ADD FOREIGN KEY ("TEN_BAN")
	  REFERENCES "C##BINHCHILI"."BAN_AN" ("TEN_BAN") ENABLE;
  ALTER TABLE "C##BINHCHILI"."BANAN_MONAN" ADD FOREIGN KEY ("TEN_MON")
	  REFERENCES "C##BINHCHILI"."MON_AN" ("TEN_MON") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISH_DATA
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."DISH_DATA" ADD CONSTRAINT "PK_DISH" FOREIGN KEY ("TEN_MON")
	  REFERENCES "C##BINHCHILI"."MON_AN" ("TEN_MON") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "C##BINHCHILI"."NHANVIEN" ADD FOREIGN KEY ("CHUC_VU")
	  REFERENCES "C##BINHCHILI"."CHUCVU" ("TEN_CHUCVU") ENABLE;
